version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
 
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  pyspark:
    image: jupyter/pyspark-notebook:latest
    hostname: pyspark
    ports:
      - "8888:8888"
    # volumes:
    #   - ./mycode.py:/home/jovyan/work/yourcode.py
    environment:
      - PYSPARK_ALLOW_INSECURE_GATEWAY=1
      - SPARK_OPTS=--master=kafka:9092
    # command: bash -c "pip install kafka-python && spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 /home/jovyan/work/mycode.py"
    depends_on:
      - kafka
