version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - mynetwork

  pyspark:
    image: jupyter/pyspark-notebook:latest
    hostname: pyspark
    ports:
      - "8888:8888"
    # volumes:
    #   - ./mycode.py:/home/jovyan/work/yourcode.py
    environment:
      - PYSPARK_ALLOW_INSECURE_GATEWAY=1
      - SPARK_OPTS=--master=kafka:9092
    # command: bash -c "pip install kafka-python && spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 /home/jovyan/work/mycode.py"
    depends_on:
      - kafka
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    hostname: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.seed_hosts=elasticsearch
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
