# Generated by Django 4.2.4 on 2023-08-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("topic_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("add_time", models.DateTimeField()),
                ("post_ids_list", models.TextField()),
            ],
            options={
                "managed": True,
            },
        ),
    ]
