# Generated by Django 4.2.4 on 2023-08-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("num_like", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("topic_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("add_time", models.DateTimeField()),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Topic_post",
            fields=[
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="topic_modeling.topic",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="topic_modeling.post",
                    ),
                ),
            ],
            options={
                "managed": True,
                "unique_together": {("topic", "post")},
            },
        ),
    ]
